plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "/Users/amyzhu/Documents/Codex/2026-09-16/new-chat/outputs/husky-robotics/_site"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]